model = "deepseek/deepseek-v4-flash"
model_reasoning_effort = "max"
# model_context_window = 380000
model_provider = "openai"
openai_base_url = "http://127.0.0.1:10109/v1"
model_catalog_json = "/home/cfd_agent/.codex/opencodex-catalog.json"
approvals_reviewer = "auto_review"
plan_mode_reasoning_effort = "max"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_glm52_m3_01"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_glm52_m3_02"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_dsv4_flash_03"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_dsv4_flash_04"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_dsv4_flash_05"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_dsv4_flash_06"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_dsv4_flash_07"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_kimik3_02"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/cfd_agentic_benchmark/codex_glm52_m3_03"]
trust_level = "trusted"

[projects."/home/harry/projects/litellm"]
trust_level = "trusted"

[projects."/mnt/ssd-SATARAID5/harry/projects/comfyui"]
trust_level = "trusted"
